"""Seed initial data – Karnataka-only stations"""
from datetime import datetime, timedelta
import random

# Karnataka stations with coordinates for map
KARNATAKA_STATIONS = [
    {"id": "KSN-BNC", "name": "Bengaluru City", "code": "SBC", "lat": 12.977, "lng": 77.572, "type": "major"},
    {"id": "KSN-YPR", "name": "Yeshwanthpur",   "code": "YPR", "lat": 13.021, "lng": 77.548, "type": "junction"},
    {"id": "KSN-KRP", "name": "KR Puram",        "code": "KRP", "lat": 13.005, "lng": 77.696, "type": "normal"},
    {"id": "KSN-KGI", "name": "Kengeri",          "code": "KGI", "lat": 12.907, "lng": 77.483, "type": "normal"},
    {"id": "KSN-MYS", "name": "Mysuru Junction",  "code": "MYS", "lat": 12.295, "lng": 76.640, "type": "major"},
    {"id": "KSN-MAQ", "name": "Mangaluru Central","code": "MAQ", "lat": 12.870, "lng": 74.843, "type": "major"},
    {"id": "KSN-UBL", "name": "Hubballi Junction","code": "UBL", "lat": 15.362, "lng": 75.124, "type": "major"},
    {"id": "KSN-DWR", "name": "Dharwad",          "code": "DWR", "lat": 15.458, "lng": 75.005, "type": "normal"},
    {"id": "KSN-BGM", "name": "Belagavi",         "code": "BGM", "lat": 15.853, "lng": 74.497, "type": "major"},
    {"id": "KSN-SMET","name": "Shivamogga",       "code": "SMET","lat": 13.930, "lng": 75.560, "type": "junction"},
    {"id": "KSN-DVG", "name": "Davangere",        "code": "DVG", "lat": 14.465, "lng": 75.919, "type": "normal"},
    {"id": "KSN-BAY", "name": "Ballari Junction", "code": "BAY", "lat": 15.139, "lng": 76.928, "type": "junction"},
    {"id": "KSN-GR",  "name": "Kalaburagi",       "code": "GR",  "lat": 17.329, "lng": 76.820, "type": "major"},
    {"id": "KSN-RC",  "name": "Raichur Junction", "code": "RC",  "lat": 16.212, "lng": 77.356, "type": "junction"},
    {"id": "KSN-HAS", "name": "Hassan",           "code": "HAS", "lat": 13.003, "lng": 76.097, "type": "normal"},
]

SAMPLE_TRAINS = [
    {
        "train_id": "TRN-001",
        "train_name": "Island Express",
        "train_number": "16527",
        "route": "Bengaluru City → Mysuru Junction",
        "source": "Bengaluru City",
        "destination": "Mysuru Junction",
        "current_station": "Kengeri",
        "next_station": "Mysuru Junction",
        "platform": "PF-2",
        "arrival_time": "09:15",
        "departure_time": "09:20",
        "speed": 95.5,
        "signal_status": "Green",
        "weather": "Clear",
        "congestion_level": "Low",
        "delay_minutes": 0,
        "detected_objects": [],
        "risk_level": "Low",
        "run_status": "running",
        "recommendation": "Normal operation. Proceed as scheduled.",
        "is_active": True,
    },
    {
        "train_id": "TRN-002",
        "train_name": "Shatabdi Express",
        "train_number": "12028",
        "route": "Bengaluru City → Hubballi Junction",
        "source": "Bengaluru City",
        "destination": "Hubballi Junction",
        "current_station": "Davangere",
        "next_station": "Hubballi Junction",
        "platform": "PF-1",
        "arrival_time": "13:45",
        "departure_time": "13:55",
        "speed": 120.0,
        "signal_status": "Yellow",
        "weather": "Cloudy",
        "congestion_level": "Medium",
        "delay_minutes": 12,
        "detected_objects": ["person_on_track"],
        "risk_level": "Critical",
        "run_status": "delayed",
        "recommendation": "EMERGENCY STOP. Person detected on track. Alert ground staff.",
        "is_active": True,
    },
    {
        "train_id": "TRN-003",
        "train_name": "Rajya Rani Express",
        "train_number": "16589",
        "route": "Bengaluru City → Mangaluru Central",
        "source": "Bengaluru City",
        "destination": "Mangaluru Central",
        "current_station": "Hassan",
        "next_station": "Mangaluru Central",
        "platform": "PF-3",
        "arrival_time": "11:30",
        "departure_time": "11:35",
        "speed": 85.0,
        "signal_status": "Green",
        "weather": "Rainy",
        "congestion_level": "High",
        "delay_minutes": 25,
        "detected_objects": ["platform_crowd"],
        "risk_level": "Medium",
        "run_status": "delayed",
        "recommendation": "Reduce speed near platform. High crowd density detected.",
        "is_active": True,
    },
    {
        "train_id": "TRN-004",
        "train_name": "Rani Chennamma Express",
        "train_number": "11301",
        "route": "Bengaluru City → Belagavi",
        "source": "Bengaluru City",
        "destination": "Belagavi",
        "current_station": "Hubballi Junction",
        "next_station": "Dharwad",
        "platform": None,
        "arrival_time": "16:10",
        "departure_time": "16:15",
        "speed": 70.0,
        "signal_status": "Red",
        "weather": "Clear",
        "congestion_level": "Low",
        "delay_minutes": 5,
        "detected_objects": ["obstacle_on_track"],
        "risk_level": "High",
        "run_status": "stopped",
        "recommendation": "Stop immediately. Obstacle detected on track. Dispatch clearing crew.",
        "is_active": True,
    },
    {
        "train_id": "TRN-005",
        "train_name": "Hampi Express",
        "train_number": "16592",
        "route": "Bengaluru City → Ballari Junction",
        "source": "Bengaluru City",
        "destination": "Ballari Junction",
        "current_station": "Ballari Junction",
        "next_station": "Kalaburagi",
        "platform": "PF-4",
        "arrival_time": "18:05",
        "departure_time": "18:15",
        "speed": 60.0,
        "signal_status": "Green",
        "weather": "Cloudy",
        "congestion_level": "Medium",
        "delay_minutes": 8,
        "detected_objects": [],
        "risk_level": "Low",
        "run_status": "running",
        "recommendation": "Normal operation. Minor delay. Monitor schedule.",
        "is_active": True,
    },
    {
        "train_id": "TRN-006",
        "train_name": "Netravati Express",
        "train_number": "16346",
        "route": "Yeshwanthpur → Raichur Junction",
        "source": "Yeshwanthpur",
        "destination": "Raichur Junction",
        "current_station": "Kalaburagi",
        "next_station": "Raichur Junction",
        "platform": "PF-1",
        "arrival_time": "21:30",
        "departure_time": "21:40",
        "speed": 110.0,
        "signal_status": "Green",
        "weather": "Clear",
        "congestion_level": "Low",
        "delay_minutes": 0,
        "detected_objects": [],
        "risk_level": "Low",
        "run_status": "running",
        "recommendation": "Normal operation. On schedule.",
        "is_active": True,
    },
]

SAMPLE_PLATFORMS = [
    {"platform_id": "PF-1", "station": "Bengaluru City", "assigned_train": "TRN-002", "status": "occupied",    "crowd_level": "Medium"},
    {"platform_id": "PF-2", "station": "Bengaluru City", "assigned_train": "TRN-001", "status": "occupied",    "crowd_level": "Low"},
    {"platform_id": "PF-3", "station": "Bengaluru City", "assigned_train": "TRN-003", "status": "occupied",    "crowd_level": "High"},
    {"platform_id": "PF-4", "station": "Bengaluru City", "assigned_train": "TRN-005", "status": "occupied",    "crowd_level": "Medium"},
    {"platform_id": "PF-5", "station": "Bengaluru City", "assigned_train": None,       "status": "available",  "crowd_level": "Low"},
    {"platform_id": "PF-6", "station": "Bengaluru City", "assigned_train": None,       "status": "maintenance","crowd_level": "Low"},
]

SAMPLE_SIGNALS = [
    {"signal_id": "SIG-001", "location": "SBC Entry North",  "status": "Green",  "controlled_track": "Track-1"},
    {"signal_id": "SIG-002", "location": "YPR Approach",     "status": "Red",    "controlled_track": "Track-2"},
    {"signal_id": "SIG-003", "location": "KRP Junction",     "status": "Yellow", "controlled_track": "Track-3"},
    {"signal_id": "SIG-004", "location": "SBC Exit South",   "status": "Green",  "controlled_track": "Track-4"},
    {"signal_id": "SIG-005", "location": "MYS Platform Exit","status": "Green",  "controlled_track": "Track-5"},
    {"signal_id": "SIG-006", "location": "UBL Level Cross",  "status": "Red",    "controlled_track": "Track-6"},
]
